"""add order fulfillment metadata and stripe checkout url config

Revision ID: 2e68722ad51c
Revises: a87410dd9923
Create Date: 2026-07-02 16:32:04.462185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e68722ad51c'
down_revision = 'a87410dd9923'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_instructions', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Seed Stripe Checkout URL config keys (editable via admin settings).
    for key, is_sensitive in [
        ("stripe.checkout_success_url", False),
        ("stripe.checkout_cancel_url", False),
    ]:
        op.execute(
            sa.text(
                """
                INSERT INTO platform_config (
                    config_key, config_value, value_type, environment, is_sensitive, is_editable
                )
                VALUES (
                    :key,
                    '""'::jsonb,
                    'string',
                    'all',
                    :is_sensitive,
                    true
                )
                ON CONFLICT DO NOTHING
                """
            ).bindparams(key=key, is_sensitive=is_sensitive)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pickup_time')
    op.drop_column('orders', 'delivery_instructions')
    # ### end Alembic commands ###
