"""clean_voucher_types_add_minimum_tier_id

Revision ID: a95e99792003
Revises: f7g8h9i0j1k2
Create Date: 2026-05-28 06:36:41.779383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a95e99792003'
down_revision = 'f7g8h9i0j1k2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_otp_sessions_customer', table_name='otp_sessions')
    op.drop_index('idx_otp_sessions_phone', table_name='otp_sessions')
    op.drop_index('idx_otp_sessions_token', table_name='otp_sessions')
    op.drop_table('otp_sessions')
    op.drop_index('idx_customer_favorites_customer', table_name='customer_favorites')
    op.drop_index('idx_customer_favorites_item', table_name='customer_favorites')
    op.drop_table('customer_favorites')
    op.drop_index('idx_gallery_card', table_name='card_gallery_images')
    op.drop_table('card_gallery_images')
    op.drop_index('idx_pin_attempts_staff', table_name='staff_pin_attempts')
    op.drop_index('idx_pin_attempts_time', table_name='staff_pin_attempts')
    op.drop_table('staff_pin_attempts')
    op.drop_index('idx_checkout_customer', table_name='checkout_sessions')
    op.drop_index('idx_checkout_expires', table_name='checkout_sessions', postgresql_where='(is_completed = false)')
    op.drop_index('idx_checkout_sessions_completed_order', table_name='checkout_sessions')
    op.drop_index('idx_checkout_sessions_store', table_name='checkout_sessions')
    op.drop_index('idx_checkout_token_hash', table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_index('idx_admin_accounts_email', table_name='admin_accounts', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_admin_accounts_is_active', table_name='admin_accounts')
    op.drop_index('idx_admin_accounts_locked_until', table_name='admin_accounts')
    op.drop_index('idx_admin_accounts_principal', table_name='admin_accounts', postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint(None, 'admin_accounts', ['principal_id'])
    op.alter_column('admin_notifications', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('admin_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_api_credentials_active', table_name='api_credentials', postgresql_where='(is_active = true)')
    op.drop_index('idx_api_credentials_key_hash', table_name='api_credentials')
    op.drop_index('idx_api_credentials_principal', table_name='api_credentials')
    op.drop_index('idx_audit_log_action', table_name='audit_log')
    op.drop_index('idx_audit_log_created', table_name='audit_log', postgresql_using='brin')
    op.drop_index('idx_audit_log_principal', table_name='audit_log')
    op.drop_index('idx_audit_log_request_id', table_name='audit_log')
    op.drop_index('idx_audit_log_resource', table_name='audit_log')
    op.drop_index('idx_audit_log_severity', table_name='audit_log')
    op.drop_index('idx_audit_log_store', table_name='audit_log')
    op.drop_index('idx_cart_line_items_menu_variant', table_name='cart_line_items')
    op.drop_index('idx_cart_lines_cart', table_name='cart_line_items')
    op.drop_index('idx_cart_lines_item', table_name='cart_line_items')
    op.create_index(op.f('ix_cart_line_items_menu_variant_id'), 'cart_line_items', ['menu_variant_id'], unique=False)
    op.drop_index('idx_content_sections_ref', table_name='content_sections')
    op.drop_index('idx_page_sections_page', table_name='content_sections')
    op.drop_index('idx_customer_addresses_country', table_name='customer_addresses')
    op.drop_index('idx_customer_addresses_customer', table_name='customer_addresses')
    op.drop_index('idx_customer_addresses_default', table_name='customer_addresses', postgresql_where='((is_default = true) AND (deleted_at IS NULL))')
    op.drop_index('idx_customer_addresses_geo', table_name='customer_addresses', postgresql_using='gist')
    op.drop_index('idx_customer_carts_activity', table_name='customer_carts')
    op.drop_index('idx_customer_carts_unique', table_name='customer_carts')
    op.create_index(op.f('ix_customer_carts_store_id'), 'customer_carts', ['store_id'], unique=False)
    op.drop_index('idx_customer_consents_customer', table_name='customer_consents')
    op.drop_index('idx_customer_consents_status', table_name='customer_consents')
    op.drop_index('idx_customer_consents_type', table_name='customer_consents')
    op.drop_index('idx_customer_consents_unique', table_name='customer_consents')
    op.alter_column('customer_daily_checkins', 'customer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('customer_daily_checkins', 'checkin_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_constraint('customer_daily_checkins_customer_id_checkin_date_key', 'customer_daily_checkins', type_='unique')
    op.drop_index('idx_checkins_customer', table_name='customer_daily_checkins')
    op.drop_index('idx_checkins_date', table_name='customer_daily_checkins')
    op.create_index(op.f('ix_customer_daily_checkins_customer_id'), 'customer_daily_checkins', ['customer_id'], unique=False)
    op.drop_constraint('customer_daily_checkins_customer_id_fkey', 'customer_daily_checkins', type_='foreignkey')
    op.create_foreign_key(None, 'customer_daily_checkins', 'customers', ['customer_id'], ['id'])
    op.drop_index('idx_customer_devices_active', table_name='customer_devices', postgresql_where='(is_active = true)')
    op.drop_index('idx_customer_devices_customer', table_name='customer_devices')
    op.drop_index('idx_customer_devices_fingerprint', table_name='customer_devices')
    op.create_unique_constraint(None, 'customer_devices', ['device_fingerprint'])
    op.drop_index('idx_customer_rewards_catalog', table_name='customer_rewards')
    op.drop_index('idx_customer_rewards_code', table_name='customer_rewards')
    op.drop_index('idx_customer_rewards_customer', table_name='customer_rewards')
    op.drop_index('idx_customer_rewards_expires', table_name='customer_rewards')
    op.drop_index('idx_customer_rewards_order', table_name='customer_rewards')
    op.drop_index('idx_customer_rewards_status', table_name='customer_rewards')
    op.drop_index('idx_customer_rewards_store', table_name='customer_rewards')
    op.drop_constraint('customer_rewards_store_id_fkey', 'customer_rewards', type_='foreignkey')
    op.create_foreign_key(None, 'customer_rewards', 'stores', ['store_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('idx_customer_vouchers_customer', table_name='customer_vouchers')
    op.drop_index('idx_customer_vouchers_definition', table_name='customer_vouchers')
    op.drop_index('idx_customer_vouchers_expires', table_name='customer_vouchers')
    op.drop_index('idx_customer_vouchers_order', table_name='customer_vouchers')
    op.drop_index('idx_customer_vouchers_status', table_name='customer_vouchers')
    op.drop_index('idx_customer_vouchers_store', table_name='customer_vouchers')
    op.create_index('idx_customer_vouchers_voucher_code', 'customer_vouchers', ['voucher_code'], unique=False)
    op.drop_constraint('customer_vouchers_store_id_fkey', 'customer_vouchers', type_='foreignkey')
    op.create_foreign_key(None, 'customer_vouchers', 'stores', ['store_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('idx_customers_created_at', table_name='customers')
    op.drop_index('idx_customers_deleted_at', table_name='customers', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_customers_email', table_name='customers', postgresql_where='((email_address IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index('idx_customers_lifetime_value', table_name='customers')
    op.drop_index('idx_customers_phone', table_name='customers', postgresql_where='((phone_number IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index('idx_customers_referral_code', table_name='customers', postgresql_where='(referral_code IS NOT NULL)')
    op.drop_index('idx_customers_referred_by', table_name='customers')
    op.drop_index('idx_customers_segment', table_name='customers')
    op.create_unique_constraint(None, 'customers', ['email_address'])
    op.create_unique_constraint(None, 'customers', ['phone_number'])
    op.drop_index('idx_dining_tables_store', table_name='dining_tables')
    op.drop_index('idx_equipment_store_id', table_name='equipment')
    op.create_index(op.f('ix_equipment_store_id'), 'equipment', ['store_id'], unique=False)
    op.drop_index('idx_equipment_maintenance_logs_equipment_id', table_name='equipment_maintenance_logs')
    op.create_index(op.f('ix_equipment_maintenance_logs_equipment_id'), 'equipment_maintenance_logs', ['equipment_id'], unique=False)
    op.alter_column('event_cards', 'rsvp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('event_cards', 'rsvp_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('event_rsvps', 'customer_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index('uq_event_rsvps_event_customer', table_name='event_rsvps')
    op.alter_column('feedback_entries', 'customer_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('feedback_entries', 'replied_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index('idx_iam_permissions_resource_action', table_name='iam_permissions')
    op.drop_index('idx_iam_principals_deleted_at', table_name='iam_principals', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_iam_principals_status', table_name='iam_principals')
    op.drop_index('idx_iam_principals_type', table_name='iam_principals')
    op.drop_index('idx_iam_roles_scope', table_name='iam_roles')
    op.drop_index('idx_info_cards_slug', table_name='information_cards')
    op.drop_index('idx_info_cards_type', table_name='information_cards')
    op.drop_index('idx_inv_categories_parent', table_name='inventory_categories')
    op.drop_index('idx_inventory_supplier', table_name='inventory_items')
    op.create_foreign_key(None, 'inventory_items', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.drop_column('inventory_items', 'store_id_temp')
    op.drop_index('idx_inv_movement_created', table_name='inventory_movement_log', postgresql_using='brin')
    op.drop_index('idx_inv_movement_item', table_name='inventory_movement_log')
    op.drop_index('idx_inv_movement_reference', table_name='inventory_movement_log')
    op.drop_index('idx_inv_movement_store', table_name='inventory_movement_log')
    op.drop_index('idx_inv_movement_type', table_name='inventory_movement_log')
    op.drop_index('idx_inventory_movement_performed_by', table_name='inventory_movement_log')
    op.create_index(op.f('ix_inventory_movement_log_performed_by'), 'inventory_movement_log', ['performed_by'], unique=False)
    op.drop_index('ix_inventory_stock_item', table_name='inventory_stock')
    op.drop_index('ix_inventory_stock_store', table_name='inventory_stock')
    op.create_index(op.f('ix_inventory_stock_inventory_item_id'), 'inventory_stock', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_stock_store_id'), 'inventory_stock', ['store_id'], unique=False)
    op.drop_index('idx_loyalty_accounts_customer', table_name='loyalty_accounts')
    op.drop_index('idx_loyalty_accounts_tier', table_name='loyalty_accounts')
    op.drop_index('idx_loyalty_ledger_account', table_name='loyalty_points_ledger')
    op.drop_index('idx_loyalty_ledger_created', table_name='loyalty_points_ledger', postgresql_using='brin')
    op.drop_index('idx_loyalty_ledger_created_by', table_name='loyalty_points_ledger')
    op.drop_index('idx_loyalty_ledger_customer', table_name='loyalty_points_ledger')
    op.drop_index('idx_loyalty_ledger_event', table_name='loyalty_points_ledger')
    op.drop_index('idx_loyalty_ledger_expires', table_name='loyalty_points_ledger')
    op.drop_index('idx_loyalty_ledger_order', table_name='loyalty_points_ledger')
    op.create_index(op.f('ix_loyalty_points_ledger_created_by'), 'loyalty_points_ledger', ['created_by'], unique=False)
    op.drop_index('idx_loyalty_tiers_min_points', table_name='loyalty_tiers')
    op.drop_index('idx_loyalty_tiers_sort', table_name='loyalty_tiers')
    op.alter_column('marketing_campaigns', 'created_by',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('idx_campaigns_scheduled', table_name='marketing_campaigns')
    op.drop_index('idx_campaigns_status', table_name='marketing_campaigns')
    op.drop_index('idx_campaigns_type', table_name='marketing_campaigns')
    op.drop_index('idx_marketing_campaigns_created_by', table_name='marketing_campaigns')
    op.create_index(op.f('ix_marketing_campaigns_created_by'), 'marketing_campaigns', ['created_by'], unique=False)
    op.drop_index('idx_menu_categories_deleted', table_name='menu_categories', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_menu_categories_display', table_name='menu_categories')
    op.drop_index('idx_menu_categories_parent', table_name='menu_categories')
    op.drop_index('idx_recipes_inventory', table_name='menu_item_recipes')
    op.drop_index('idx_recipes_item', table_name='menu_item_recipes')
    op.drop_index('idx_recipes_unique', table_name='menu_item_recipes')
    op.drop_index('idx_recipes_variant', table_name='menu_item_recipes')
    op.drop_index('idx_menu_items_available', table_name='menu_items', postgresql_where='((is_available = true) AND (deleted_at IS NULL))')
    op.drop_index('idx_menu_items_deleted', table_name='menu_items', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_menu_items_featured', table_name='menu_items', postgresql_where='((is_featured = true) AND (deleted_at IS NULL))')
    op.drop_index('idx_menu_items_search', table_name='menu_items', postgresql_using='gin')
    op.drop_index('idx_modifier_groups_item', table_name='menu_modifier_groups')
    op.drop_index('idx_modifier_groups_order', table_name='menu_modifier_groups')
    op.drop_index('idx_modifier_options_default', table_name='menu_modifier_options', postgresql_where='(is_default = true)')
    op.drop_index('idx_modifier_options_group', table_name='menu_modifier_options')
    op.drop_index('idx_menu_variants_parent', table_name='menu_variants')
    op.alter_column('notification_delivery_log', 'recipient_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('idx_notification_delivery_channel', table_name='notification_delivery_log')
    op.drop_index('idx_notification_delivery_device', table_name='notification_delivery_log')
    op.drop_index('idx_notification_delivery_message', table_name='notification_delivery_log')
    op.drop_index('idx_notification_delivery_status', table_name='notification_delivery_log')
    op.create_index(op.f('ix_notification_delivery_log_device_id'), 'notification_delivery_log', ['device_id'], unique=False)
    op.drop_index('idx_notification_messages_campaign', table_name='notification_messages')
    op.drop_index('idx_notification_messages_customer', table_name='notification_messages')
    op.drop_index('idx_notification_messages_expires', table_name='notification_messages')
    op.drop_index('idx_notification_messages_type', table_name='notification_messages')
    op.drop_index('idx_notification_messages_unread', table_name='notification_messages', postgresql_where='(is_read = false)')
    op.drop_constraint('notification_messages_campaign_id_fkey', 'notification_messages', type_='foreignkey')
    op.drop_index('idx_notification_prefs_customer', table_name='notification_preferences')
    op.drop_constraint('notification_preferences_customer_id_channel_message_catego_key', 'notification_preferences', type_='unique')
    op.create_unique_constraint('uq_notification_preferences', 'notification_preferences', ['customer_id', 'channel', 'message_category'])
    op.alter_column('notification_templates', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_constraint('notification_templates_created_by_fkey', 'notification_templates', type_='foreignkey')
    op.drop_column('notification_templates', 'audience')
    op.drop_column('notification_templates', 'message_type')
    op.drop_column('notification_templates', 'is_active')
    op.drop_column('notification_templates', 'created_by')
    op.drop_index('idx_order_adjustments_approved_by', table_name='order_adjustments')
    op.drop_index('idx_order_adjustments_order', table_name='order_adjustments')
    op.drop_index('idx_order_adjustments_type', table_name='order_adjustments')
    op.create_index(op.f('ix_order_adjustments_approved_by'), 'order_adjustments', ['approved_by'], unique=False)
    op.drop_index('idx_fulfillment_assigned', table_name='order_fulfillment')
    op.drop_index('idx_fulfillment_order', table_name='order_fulfillment')
    op.drop_index('idx_fulfillment_provider', table_name='order_fulfillment')
    op.drop_index('idx_fulfillment_status', table_name='order_fulfillment')
    op.drop_index('idx_order_fulfillment_address', table_name='order_fulfillment')
    op.create_index(op.f('ix_order_fulfillment_customer_address_id'), 'order_fulfillment', ['customer_address_id'], unique=False)
    op.drop_index('idx_order_line_items_menu_variant', table_name='order_line_items')
    op.drop_index('idx_order_line_items_served_by', table_name='order_line_items')
    op.drop_index('idx_order_lines_fulfillment', table_name='order_line_items')
    op.drop_index('idx_order_lines_menu_item', table_name='order_line_items')
    op.drop_index('idx_order_lines_order', table_name='order_line_items')
    op.create_index(op.f('ix_order_line_items_menu_variant_id'), 'order_line_items', ['menu_variant_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_served_by'), 'order_line_items', ['served_by'], unique=False)
    op.drop_index('idx_order_status_log_created', table_name='order_status_log', postgresql_using='brin')
    op.drop_index('idx_order_status_log_order', table_name='order_status_log')
    op.drop_index('idx_orders_cancelled_by_staff', table_name='orders')
    op.drop_index('idx_orders_channel', table_name='orders')
    op.drop_index('idx_orders_created', table_name='orders', postgresql_using='brin')
    op.drop_index('idx_orders_customer', table_name='orders')
    op.drop_index('idx_orders_number', table_name='orders')
    op.drop_index('idx_orders_payment_status', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_store_status_created', table_name='orders')
    op.drop_index('idx_orders_table', table_name='orders')
    op.create_index('idx_orders_deleted_at', 'orders', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_orders_device_fingerprint', 'orders', ['device_fingerprint'], unique=False, postgresql_where=sa.text('device_fingerprint IS NOT NULL'))
    op.add_column('payment_events', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index('idx_payment_events_created', table_name='payment_events', postgresql_using='brin')
    op.drop_index('idx_payment_events_payment', table_name='payment_events')
    op.drop_index('idx_payment_methods_active', table_name='payment_methods', postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    op.drop_index('idx_payment_methods_customer', table_name='payment_methods')
    op.drop_index('idx_payment_methods_default', table_name='payment_methods', postgresql_where='((is_default = true) AND (is_active = true) AND (deleted_at IS NULL))')
    op.drop_index('idx_payments_created', table_name='payments', postgresql_using='brin')
    op.drop_index('idx_payments_idempotency', table_name='payments')
    op.drop_index('idx_payments_method', table_name='payments')
    op.drop_index('idx_payments_order', table_name='payments')
    op.drop_index('idx_payments_provider_tx', table_name='payments')
    op.drop_index('idx_payments_settled', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.create_index(op.f('ix_payments_payment_method_id'), 'payments', ['payment_method_id'], unique=False)
    op.drop_index('idx_platform_config_env', table_name='platform_config')
    op.drop_index('idx_platform_config_modified_by', table_name='platform_config')
    op.drop_constraint('platform_config_key_unique', 'platform_config', type_='unique')
    op.create_index(op.f('ix_platform_config_modified_by'), 'platform_config', ['modified_by'], unique=False)
    op.drop_index('idx_po_lines_item', table_name='purchase_order_lines')
    op.drop_index('idx_po_lines_order', table_name='purchase_order_lines')
    op.alter_column('purchase_orders', 'created_by',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('idx_purchase_orders_created_by', table_name='purchase_orders')
    op.drop_index('idx_purchase_orders_number', table_name='purchase_orders')
    op.drop_index('idx_purchase_orders_status', table_name='purchase_orders')
    op.drop_index('idx_purchase_orders_store', table_name='purchase_orders')
    op.drop_index('idx_purchase_orders_supplier', table_name='purchase_orders')
    op.create_index(op.f('ix_purchase_orders_created_by'), 'purchase_orders', ['created_by'], unique=False)
    op.drop_index('idx_referral_events_wallet', table_name='referral_events')
    op.drop_constraint('referral_events_referrer_customer_id_invitee_customer_id_key', 'referral_events', type_='unique')
    op.create_index(op.f('ix_referral_events_reward_wallet_entry_id'), 'referral_events', ['reward_wallet_entry_id'], unique=False)
    op.drop_column('referral_events', 'reward_paid')
    op.drop_column('referral_events', 'reward_points')
    op.drop_column('referral_events', 'invitee_order_count')
    op.alter_column('refunds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_refunds_approved_by', table_name='refunds')
    op.drop_index('idx_refunds_created', table_name='refunds', postgresql_using='brin')
    op.drop_index('idx_refunds_order', table_name='refunds')
    op.drop_index('idx_refunds_payment', table_name='refunds')
    op.drop_index('idx_refunds_status', table_name='refunds')
    op.create_index(op.f('ix_refunds_approved_by'), 'refunds', ['approved_by'], unique=False)
    op.drop_index('idx_reservations_customer', table_name='reservations')
    op.drop_index('idx_reservations_store', table_name='reservations')
    op.drop_index('idx_reservations_table', table_name='reservations')
    op.create_index(op.f('ix_reservations_customer_id'), 'reservations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reservations_dining_table_id'), 'reservations', ['dining_table_id'], unique=False)
    op.create_index(op.f('ix_reservations_store_id'), 'reservations', ['store_id'], unique=False)
    op.alter_column('reward_catalog', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_reward_catalog_active', table_name='reward_catalog', postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    op.drop_index('idx_reward_catalog_deleted', table_name='reward_catalog', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_reward_catalog_menu_item', table_name='reward_catalog')
    op.drop_index('idx_reward_catalog_tier', table_name='reward_catalog')
    op.drop_index('idx_reward_catalog_type', table_name='reward_catalog')
    op.create_index(op.f('ix_reward_catalog_menu_item_id'), 'reward_catalog', ['menu_item_id'], unique=False)
    op.drop_index('idx_role_assignments_active', table_name='role_assignments', postgresql_where='(is_active = true)')
    op.drop_index('idx_role_assignments_assigned_by', table_name='role_assignments')
    op.drop_index('idx_role_assignments_assignee', table_name='role_assignments')
    op.drop_index('idx_role_assignments_effective', table_name='role_assignments')
    op.drop_index('idx_role_assignments_role', table_name='role_assignments')
    op.create_index(op.f('ix_role_assignments_assigned_by'), 'role_assignments', ['assigned_by'], unique=False)
    op.drop_index('idx_role_permission_granted_by', table_name='role_permission')
    op.drop_index('idx_scheduled_jobs_active', table_name='scheduled_jobs', postgresql_where='(is_active = true)')
    op.drop_index('idx_scheduled_jobs_next_run', table_name='scheduled_jobs')
    op.alter_column('splash_screens', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index('idx_splash_screens_active', table_name='splash_screens', postgresql_where='(is_active = true)')
    op.drop_index('idx_splash_screens_date', table_name='splash_screens')
    op.drop_index('idx_staff_profiles_active', table_name='staff_profiles', postgresql_where='(is_active = true)')
    op.drop_index('idx_staff_profiles_deleted', table_name='staff_profiles', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_staff_profiles_role', table_name='staff_profiles')
    op.drop_index('idx_staff_profiles_store', table_name='staff_profiles')
    op.create_unique_constraint('uq_staff_profiles_display_name_store_id', 'staff_profiles', ['display_name', 'store_id'])
    op.drop_index('idx_staff_shifts_staff', table_name='staff_shifts')
    op.drop_index('idx_staff_shifts_store', table_name='staff_shifts')
    op.create_index(op.f('ix_staff_shifts_staff_id'), 'staff_shifts', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_shifts_store_id'), 'staff_shifts', ['store_id'], unique=False)
    op.drop_index('idx_staff_time_events_approved_by', table_name='staff_time_events')
    op.drop_index('idx_staff_time_events_staff', table_name='staff_time_events')
    op.drop_index('idx_staff_time_events_store', table_name='staff_time_events')
    op.drop_index('idx_staff_time_events_timestamp', table_name='staff_time_events')
    op.drop_index('idx_staff_time_events_type', table_name='staff_time_events')
    op.create_index(op.f('ix_staff_time_events_approved_by'), 'staff_time_events', ['approved_by'], unique=False)
    op.drop_index('idx_store_assignments_assignee', table_name='store_assignments')
    op.drop_index('idx_store_assignments_primary', table_name='store_assignments', postgresql_where='(is_primary = true)')
    op.drop_index('idx_store_assignments_store', table_name='store_assignments')
    op.drop_index('idx_store_config_store_key', table_name='store_configuration')
    op.drop_index('idx_store_hours_closed', table_name='store_operating_hours', postgresql_where='(is_closed = true)')
    op.drop_index('idx_store_hours_store_day', table_name='store_operating_hours')
    op.drop_index('idx_store_special_store_date', table_name='store_special_hours')
    op.alter_column('stores', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_stores_active', table_name='stores')
    op.drop_index('idx_stores_brand', table_name='stores')
    op.drop_index('idx_stores_country', table_name='stores')
    op.drop_index('idx_stores_geo', table_name='stores', postgresql_using='gist')
    op.drop_index('idx_suppliers_name', table_name='suppliers')
    op.drop_index('idx_suppliers_store', table_name='suppliers')
    op.drop_index('idx_survey_answers_question', table_name='survey_answers')
    op.drop_index('idx_survey_answers_response', table_name='survey_answers')
    op.drop_index('idx_survey_definitions_active', table_name='survey_definitions', postgresql_where='(is_active = true)')
    op.drop_index('idx_survey_definitions_created_by', table_name='survey_definitions')
    op.drop_index('idx_survey_definitions_key', table_name='survey_definitions')
    op.create_index(op.f('ix_survey_definitions_created_by'), 'survey_definitions', ['created_by'], unique=False)
    op.create_index(op.f('ix_survey_definitions_reward_voucher_id'), 'survey_definitions', ['reward_voucher_id'], unique=False)
    op.drop_index('idx_survey_questions_order', table_name='survey_questions')
    op.drop_index('idx_survey_questions_survey', table_name='survey_questions')
    op.drop_index('idx_survey_responses_created', table_name='survey_responses', postgresql_using='brin')
    op.drop_index('idx_survey_responses_customer', table_name='survey_responses')
    op.drop_index('idx_survey_responses_nps', table_name='survey_responses')
    op.drop_index('idx_survey_responses_retention', table_name='survey_responses')
    op.drop_index('idx_survey_responses_survey', table_name='survey_responses')
    op.drop_index('idx_health_metrics_dimensions', table_name='system_health_metrics', postgresql_using='gin')
    op.drop_index('idx_health_metrics_name', table_name='system_health_metrics')
    op.drop_index('idx_health_metrics_store', table_name='system_health_metrics')
    op.drop_index('idx_table_status_order', table_name='table_status_snapshot')
    op.drop_index('idx_table_status_staff', table_name='table_status_snapshot')
    op.drop_index('idx_table_status_store', table_name='table_status_snapshot')
    op.alter_column('tip_allocations', 'staff_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('idx_tip_allocations_order', table_name='tip_allocations')
    op.drop_index('idx_tip_allocations_staff', table_name='tip_allocations')
    op.drop_constraint('tip_allocations_staff_id_fkey', 'tip_allocations', type_='foreignkey')
    op.create_foreign_key(None, 'tip_allocations', 'staff_profiles', ['staff_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_token_blacklist_principal', table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_principal_id'), 'token_blacklist', ['principal_id'], unique=False)
    op.alter_column('translation_cache', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('translation_cache', 'hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('idx_translation_cache_lookup', table_name='translation_cache')
    op.alter_column('translations', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('translations', 'table_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('translations', 'record_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('translations', 'column_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index('idx_translations_locale', table_name='translations')
    op.drop_index('idx_translations_record', table_name='translations')
    op.add_column('voucher_definitions', sa.Column('minimum_tier_id', sa.Integer(), nullable=True))
    op.drop_index('idx_voucher_definitions_active', table_name='voucher_definitions', postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    op.drop_index('idx_voucher_definitions_category', table_name='voucher_definitions')
    op.drop_index('idx_voucher_definitions_created_by', table_name='voucher_definitions')
    op.drop_index('idx_voucher_definitions_deleted', table_name='voucher_definitions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_voucher_definitions_menu_item', table_name='voucher_definitions')
    op.drop_index('idx_voucher_definitions_scope', table_name='voucher_definitions')
    op.drop_index('idx_voucher_definitions_type', table_name='voucher_definitions')
    op.drop_index('idx_voucher_definitions_valid', table_name='voucher_definitions')
    op.create_index(op.f('ix_voucher_definitions_category_id'), 'voucher_definitions', ['category_id'], unique=False)
    op.create_index(op.f('ix_voucher_definitions_created_by'), 'voucher_definitions', ['created_by'], unique=False)
    op.create_index(op.f('ix_voucher_definitions_menu_item_id'), 'voucher_definitions', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_voucher_definitions_minimum_tier_id'), 'voucher_definitions', ['minimum_tier_id'], unique=False)
    op.create_foreign_key(None, 'voucher_definitions', 'loyalty_tiers', ['minimum_tier_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_wallet_ledger_created', table_name='wallet_ledger_entries', postgresql_using='brin')
    op.drop_index('idx_wallet_ledger_reference', table_name='wallet_ledger_entries')
    op.drop_index('idx_wallet_ledger_wallet', table_name='wallet_ledger_entries')
    op.create_index('idx_wallet_ledger_entries_created_at', 'wallet_ledger_entries', ['created_at'], unique=False)
    op.drop_index('idx_wallets_customer', table_name='wallets')
    op.drop_index('idx_wallets_frozen', table_name='wallets')
    op.drop_index('idx_wallets_frozen_by', table_name='wallets')
    op.create_index(op.f('ix_wallets_frozen_by'), 'wallets', ['frozen_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_frozen_by'), table_name='wallets')
    op.create_index('idx_wallets_frozen_by', 'wallets', ['frozen_by'], unique=False)
    op.create_index('idx_wallets_frozen', 'wallets', ['is_frozen'], unique=False)
    op.create_index('idx_wallets_customer', 'wallets', ['customer_id'], unique=True)
    op.drop_index('idx_wallet_ledger_entries_created_at', table_name='wallet_ledger_entries')
    op.create_index('idx_wallet_ledger_wallet', 'wallet_ledger_entries', ['wallet_id'], unique=False)
    op.create_index('idx_wallet_ledger_reference', 'wallet_ledger_entries', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_wallet_ledger_created', 'wallet_ledger_entries', ['created_at'], unique=False, postgresql_using='brin')
    op.drop_constraint(None, 'voucher_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_voucher_definitions_minimum_tier_id'), table_name='voucher_definitions')
    op.drop_index(op.f('ix_voucher_definitions_menu_item_id'), table_name='voucher_definitions')
    op.drop_index(op.f('ix_voucher_definitions_created_by'), table_name='voucher_definitions')
    op.drop_index(op.f('ix_voucher_definitions_category_id'), table_name='voucher_definitions')
    op.create_index('idx_voucher_definitions_valid', 'voucher_definitions', ['valid_from', 'valid_until'], unique=False)
    op.create_index('idx_voucher_definitions_type', 'voucher_definitions', ['voucher_type'], unique=False)
    op.create_index('idx_voucher_definitions_scope', 'voucher_definitions', ['scope'], unique=False)
    op.create_index('idx_voucher_definitions_menu_item', 'voucher_definitions', ['menu_item_id'], unique=False)
    op.create_index('idx_voucher_definitions_deleted', 'voucher_definitions', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_voucher_definitions_created_by', 'voucher_definitions', ['created_by'], unique=False)
    op.create_index('idx_voucher_definitions_category', 'voucher_definitions', ['category_id'], unique=False)
    op.create_index('idx_voucher_definitions_active', 'voucher_definitions', ['is_active'], unique=False, postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    op.drop_column('voucher_definitions', 'minimum_tier_id')
    op.create_index('idx_translations_record', 'translations', ['table_name', 'record_id', 'locale'], unique=False)
    op.create_index('idx_translations_locale', 'translations', ['locale'], unique=False)
    op.alter_column('translations', 'column_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('translations', 'record_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('translations', 'table_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('translations', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_translation_cache_lookup', 'translation_cache', ['source_locale', 'target_locale', 'hash'], unique=False)
    op.alter_column('translation_cache', 'hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('translation_cache', 'id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_token_blacklist_principal_id'), table_name='token_blacklist')
    op.create_index('idx_token_blacklist_principal', 'token_blacklist', ['principal_id'], unique=False)
    op.drop_constraint(None, 'tip_allocations', type_='foreignkey')
    op.create_foreign_key('tip_allocations_staff_id_fkey', 'tip_allocations', 'staff_profiles', ['staff_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_tip_allocations_staff', 'tip_allocations', ['staff_id'], unique=False)
    op.create_index('idx_tip_allocations_order', 'tip_allocations', ['order_id'], unique=False)
    op.alter_column('tip_allocations', 'staff_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index('idx_table_status_store', 'table_status_snapshot', ['store_id'], unique=False)
    op.create_index('idx_table_status_staff', 'table_status_snapshot', ['server_staff_id'], unique=False)
    op.create_index('idx_table_status_order', 'table_status_snapshot', ['current_order_id'], unique=False)
    op.create_index('idx_health_metrics_store', 'system_health_metrics', ['store_id'], unique=False)
    op.create_index('idx_health_metrics_name', 'system_health_metrics', ['metric_name', sa.literal_column('bucket_start DESC')], unique=False)
    op.create_index('idx_health_metrics_dimensions', 'system_health_metrics', ['dimensions'], unique=False, postgresql_using='gin')
    op.create_index('idx_survey_responses_survey', 'survey_responses', ['survey_id'], unique=False)
    op.create_index('idx_survey_responses_retention', 'survey_responses', ['data_retention_until'], unique=False)
    op.create_index('idx_survey_responses_nps', 'survey_responses', ['nps_score'], unique=False)
    op.create_index('idx_survey_responses_customer', 'survey_responses', ['customer_id'], unique=False)
    op.create_index('idx_survey_responses_created', 'survey_responses', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_survey_questions_survey', 'survey_questions', ['survey_id'], unique=False)
    op.create_index('idx_survey_questions_order', 'survey_questions', ['display_order'], unique=False)
    op.drop_index(op.f('ix_survey_definitions_reward_voucher_id'), table_name='survey_definitions')
    op.drop_index(op.f('ix_survey_definitions_created_by'), table_name='survey_definitions')
    op.create_index('idx_survey_definitions_key', 'survey_definitions', ['survey_key'], unique=True)
    op.create_index('idx_survey_definitions_created_by', 'survey_definitions', ['created_by'], unique=False)
    op.create_index('idx_survey_definitions_active', 'survey_definitions', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_survey_answers_response', 'survey_answers', ['response_id'], unique=False)
    op.create_index('idx_survey_answers_question', 'survey_answers', ['question_id'], unique=False)
    op.create_index('idx_suppliers_store', 'suppliers', ['store_id'], unique=False)
    op.create_index('idx_suppliers_name', 'suppliers', ['supplier_name'], unique=False)
    op.create_index('idx_stores_geo', 'stores', [sa.literal_column('point(longitude::double precision, latitude::double precision)')], unique=False, postgresql_using='gist')
    op.create_index('idx_stores_country', 'stores', ['country_code'], unique=False)
    op.create_index('idx_stores_brand', 'stores', ['brand_name'], unique=False)
    op.create_index('idx_stores_active', 'stores', ['is_active'], unique=False)
    op.alter_column('stores', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_store_special_store_date', 'store_special_hours', ['store_id', 'special_date'], unique=False)
    op.create_index('idx_store_hours_store_day', 'store_operating_hours', ['store_id', 'day_of_week'], unique=False)
    op.create_index('idx_store_hours_closed', 'store_operating_hours', ['is_closed'], unique=False, postgresql_where='(is_closed = true)')
    op.create_index('idx_store_config_store_key', 'store_configuration', ['store_id', 'config_key'], unique=False)
    op.create_index('idx_store_assignments_store', 'store_assignments', ['store_id'], unique=False)
    op.create_index('idx_store_assignments_primary', 'store_assignments', ['assignee_id'], unique=False, postgresql_where='(is_primary = true)')
    op.create_index('idx_store_assignments_assignee', 'store_assignments', ['assignee_id'], unique=False)
    op.drop_index(op.f('ix_staff_time_events_approved_by'), table_name='staff_time_events')
    op.create_index('idx_staff_time_events_type', 'staff_time_events', ['event_type'], unique=False)
    op.create_index('idx_staff_time_events_timestamp', 'staff_time_events', ['event_timestamp'], unique=False)
    op.create_index('idx_staff_time_events_store', 'staff_time_events', ['store_id'], unique=False)
    op.create_index('idx_staff_time_events_staff', 'staff_time_events', ['staff_id'], unique=False)
    op.create_index('idx_staff_time_events_approved_by', 'staff_time_events', ['approved_by'], unique=False)
    op.drop_index(op.f('ix_staff_shifts_store_id'), table_name='staff_shifts')
    op.drop_index(op.f('ix_staff_shifts_staff_id'), table_name='staff_shifts')
    op.create_index('idx_staff_shifts_store', 'staff_shifts', ['store_id'], unique=False)
    op.create_index('idx_staff_shifts_staff', 'staff_shifts', ['staff_id'], unique=False)
    op.drop_constraint('uq_staff_profiles_display_name_store_id', 'staff_profiles', type_='unique')
    op.create_index('idx_staff_profiles_store', 'staff_profiles', ['store_id'], unique=False)
    op.create_index('idx_staff_profiles_role', 'staff_profiles', ['role'], unique=False)
    op.create_index('idx_staff_profiles_deleted', 'staff_profiles', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_staff_profiles_active', 'staff_profiles', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_splash_screens_date', 'splash_screens', ['active_from', 'active_until'], unique=False)
    op.create_index('idx_splash_screens_active', 'splash_screens', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('splash_screens', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_index('idx_scheduled_jobs_next_run', 'scheduled_jobs', ['next_run_at'], unique=False)
    op.create_index('idx_scheduled_jobs_active', 'scheduled_jobs', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_role_permission_granted_by', 'role_permission', ['granted_by'], unique=False)
    op.drop_index(op.f('ix_role_assignments_assigned_by'), table_name='role_assignments')
    op.create_index('idx_role_assignments_role', 'role_assignments', ['role_id'], unique=False)
    op.create_index('idx_role_assignments_effective', 'role_assignments', ['effective_from', 'effective_to'], unique=False)
    op.create_index('idx_role_assignments_assignee', 'role_assignments', ['assignee_id'], unique=False)
    op.create_index('idx_role_assignments_assigned_by', 'role_assignments', ['assigned_by'], unique=False)
    op.create_index('idx_role_assignments_active', 'role_assignments', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_reward_catalog_menu_item_id'), table_name='reward_catalog')
    op.create_index('idx_reward_catalog_type', 'reward_catalog', ['reward_type'], unique=False)
    op.create_index('idx_reward_catalog_tier', 'reward_catalog', ['minimum_tier_id'], unique=False)
    op.create_index('idx_reward_catalog_menu_item', 'reward_catalog', ['menu_item_id'], unique=False)
    op.create_index('idx_reward_catalog_deleted', 'reward_catalog', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_reward_catalog_active', 'reward_catalog', ['is_active'], unique=False, postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    op.alter_column('reward_catalog', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_reservations_store_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_dining_table_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_customer_id'), table_name='reservations')
    op.create_index('idx_reservations_table', 'reservations', ['dining_table_id'], unique=False)
    op.create_index('idx_reservations_store', 'reservations', ['store_id'], unique=False)
    op.create_index('idx_reservations_customer', 'reservations', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_refunds_approved_by'), table_name='refunds')
    op.create_index('idx_refunds_status', 'refunds', ['status'], unique=False)
    op.create_index('idx_refunds_payment', 'refunds', ['payment_id'], unique=False)
    op.create_index('idx_refunds_order', 'refunds', ['order_id'], unique=False)
    op.create_index('idx_refunds_created', 'refunds', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_refunds_approved_by', 'refunds', ['approved_by'], unique=False)
    op.alter_column('refunds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('referral_events', sa.Column('invitee_order_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('referral_events', sa.Column('reward_points', sa.NUMERIC(precision=12, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('referral_events', sa.Column('reward_paid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_referral_events_reward_wallet_entry_id'), table_name='referral_events')
    op.create_unique_constraint('referral_events_referrer_customer_id_invitee_customer_id_key', 'referral_events', ['referrer_customer_id', 'invitee_customer_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_referral_events_wallet', 'referral_events', ['reward_wallet_entry_id'], unique=False)
    op.drop_index(op.f('ix_purchase_orders_created_by'), table_name='purchase_orders')
    op.create_index('idx_purchase_orders_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index('idx_purchase_orders_store', 'purchase_orders', ['store_id'], unique=False)
    op.create_index('idx_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('idx_purchase_orders_number', 'purchase_orders', ['po_number'], unique=True)
    op.create_index('idx_purchase_orders_created_by', 'purchase_orders', ['created_by'], unique=False)
    op.alter_column('purchase_orders', 'created_by',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index('idx_po_lines_order', 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_index('idx_po_lines_item', 'purchase_order_lines', ['inventory_item_id'], unique=False)
    op.drop_index(op.f('ix_platform_config_modified_by'), table_name='platform_config')
    op.create_unique_constraint('platform_config_key_unique', 'platform_config', ['config_key'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_platform_config_modified_by', 'platform_config', ['modified_by'], unique=False)
    op.create_index('idx_platform_config_env', 'platform_config', ['environment'], unique=False)
    op.drop_index(op.f('ix_payments_payment_method_id'), table_name='payments')
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_settled', 'payments', ['settled_at'], unique=False)
    op.create_index('idx_payments_provider_tx', 'payments', ['provider_transaction_id'], unique=False)
    op.create_index('idx_payments_order', 'payments', ['order_id'], unique=False)
    op.create_index('idx_payments_method', 'payments', ['payment_method_id'], unique=False)
    op.create_index('idx_payments_idempotency', 'payments', ['idempotency_key'], unique=True)
    op.create_index('idx_payments_created', 'payments', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_payment_methods_default', 'payment_methods', ['customer_id'], unique=True, postgresql_where='((is_default = true) AND (is_active = true) AND (deleted_at IS NULL))')
    op.create_index('idx_payment_methods_customer', 'payment_methods', ['customer_id'], unique=False)
    op.create_index('idx_payment_methods_active', 'payment_methods', ['is_active'], unique=False, postgresql_where='((is_active = true) AND (deleted_at IS NULL))')
    op.create_index('idx_payment_events_payment', 'payment_events', ['payment_id'], unique=False)
    op.create_index('idx_payment_events_created', 'payment_events', ['created_at'], unique=False, postgresql_using='brin')
    op.drop_column('payment_events', 'updated_at')
    op.drop_index('idx_orders_device_fingerprint', table_name='orders', postgresql_where=sa.text('device_fingerprint IS NOT NULL'))
    op.drop_index('idx_orders_deleted_at', table_name='orders', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_orders_table', 'orders', ['dining_table_id'], unique=False)
    op.create_index('idx_orders_store_status_created', 'orders', ['store_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index('idx_orders_number', 'orders', ['order_number'], unique=True)
    op.create_index('idx_orders_customer', 'orders', ['customer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_orders_created', 'orders', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_orders_channel', 'orders', ['order_channel'], unique=False)
    op.create_index('idx_orders_cancelled_by_staff', 'orders', ['cancelled_by_staff_id'], unique=False)
    op.create_index('idx_order_status_log_order', 'order_status_log', ['order_id'], unique=False)
    op.create_index('idx_order_status_log_created', 'order_status_log', ['created_at'], unique=False, postgresql_using='brin')
    op.drop_index(op.f('ix_order_line_items_served_by'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_menu_variant_id'), table_name='order_line_items')
    op.create_index('idx_order_lines_order', 'order_line_items', ['order_id'], unique=False)
    op.create_index('idx_order_lines_menu_item', 'order_line_items', ['menu_item_id'], unique=False)
    op.create_index('idx_order_lines_fulfillment', 'order_line_items', ['fulfillment_status'], unique=False)
    op.create_index('idx_order_line_items_served_by', 'order_line_items', ['served_by'], unique=False)
    op.create_index('idx_order_line_items_menu_variant', 'order_line_items', ['menu_variant_id'], unique=False)
    op.drop_index(op.f('ix_order_fulfillment_customer_address_id'), table_name='order_fulfillment')
    op.create_index('idx_order_fulfillment_address', 'order_fulfillment', ['customer_address_id'], unique=False)
    op.create_index('idx_fulfillment_status', 'order_fulfillment', ['status'], unique=False)
    op.create_index('idx_fulfillment_provider', 'order_fulfillment', ['delivery_provider'], unique=False)
    op.create_index('idx_fulfillment_order', 'order_fulfillment', ['order_id'], unique=True)
    op.create_index('idx_fulfillment_assigned', 'order_fulfillment', ['assigned_staff_id'], unique=False)
    op.drop_index(op.f('ix_order_adjustments_approved_by'), table_name='order_adjustments')
    op.create_index('idx_order_adjustments_type', 'order_adjustments', ['adjustment_type'], unique=False)
    op.create_index('idx_order_adjustments_order', 'order_adjustments', ['order_id'], unique=False)
    op.create_index('idx_order_adjustments_approved_by', 'order_adjustments', ['approved_by'], unique=False)
    op.add_column('notification_templates', sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('notification_templates', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_templates', sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notification_templates', sa.Column('audience', sa.VARCHAR(length=50), server_default=sa.text("'all'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key('notification_templates_created_by_fkey', 'notification_templates', 'admin_accounts', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('notification_templates', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint('uq_notification_preferences', 'notification_preferences', type_='unique')
    op.create_unique_constraint('notification_preferences_customer_id_channel_message_catego_key', 'notification_preferences', ['customer_id', 'channel', 'message_category'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_notification_prefs_customer', 'notification_preferences', ['customer_id'], unique=False)
    op.create_foreign_key('notification_messages_campaign_id_fkey', 'notification_messages', 'marketing_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_notification_messages_unread', 'notification_messages', ['customer_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index('idx_notification_messages_type', 'notification_messages', ['message_type'], unique=False)
    op.create_index('idx_notification_messages_expires', 'notification_messages', ['expires_at'], unique=False)
    op.create_index('idx_notification_messages_customer', 'notification_messages', ['customer_id'], unique=False)
    op.create_index('idx_notification_messages_campaign', 'notification_messages', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_notification_delivery_log_device_id'), table_name='notification_delivery_log')
    op.create_index('idx_notification_delivery_status', 'notification_delivery_log', ['status'], unique=False)
    op.create_index('idx_notification_delivery_message', 'notification_delivery_log', ['message_id'], unique=False)
    op.create_index('idx_notification_delivery_device', 'notification_delivery_log', ['device_id'], unique=False)
    op.create_index('idx_notification_delivery_channel', 'notification_delivery_log', ['channel'], unique=False)
    op.alter_column('notification_delivery_log', 'recipient_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('idx_menu_variants_parent', 'menu_variants', ['parent_item_id'], unique=False)
    op.create_index('idx_modifier_options_group', 'menu_modifier_options', ['modifier_group_id'], unique=False)
    op.create_index('idx_modifier_options_default', 'menu_modifier_options', ['is_default'], unique=False, postgresql_where='(is_default = true)')
    op.create_index('idx_modifier_groups_order', 'menu_modifier_groups', ['display_order'], unique=False)
    op.create_index('idx_modifier_groups_item', 'menu_modifier_groups', ['menu_item_id'], unique=False)
    op.create_index('idx_menu_items_search', 'menu_items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_menu_items_featured', 'menu_items', ['is_featured'], unique=False, postgresql_where='((is_featured = true) AND (deleted_at IS NULL))')
    op.create_index('idx_menu_items_deleted', 'menu_items', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_menu_items_available', 'menu_items', ['is_available'], unique=False, postgresql_where='((is_available = true) AND (deleted_at IS NULL))')
    op.create_index('idx_recipes_variant', 'menu_item_recipes', ['menu_variant_id'], unique=False)
    op.create_index('idx_recipes_unique', 'menu_item_recipes', ['menu_item_id', 'menu_variant_id', 'inventory_item_id'], unique=True)
    op.create_index('idx_recipes_item', 'menu_item_recipes', ['menu_item_id'], unique=False)
    op.create_index('idx_recipes_inventory', 'menu_item_recipes', ['inventory_item_id'], unique=False)
    op.create_index('idx_menu_categories_parent', 'menu_categories', ['parent_category_id'], unique=False)
    op.create_index('idx_menu_categories_display', 'menu_categories', ['display_order'], unique=False)
    op.create_index('idx_menu_categories_deleted', 'menu_categories', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_marketing_campaigns_created_by'), table_name='marketing_campaigns')
    op.create_index('idx_marketing_campaigns_created_by', 'marketing_campaigns', ['created_by'], unique=False)
    op.create_index('idx_campaigns_type', 'marketing_campaigns', ['campaign_type'], unique=False)
    op.create_index('idx_campaigns_status', 'marketing_campaigns', ['status'], unique=False)
    op.create_index('idx_campaigns_scheduled', 'marketing_campaigns', ['scheduled_at'], unique=False)
    op.alter_column('marketing_campaigns', 'created_by',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index('idx_loyalty_tiers_sort', 'loyalty_tiers', ['sort_order'], unique=False)
    op.create_index('idx_loyalty_tiers_min_points', 'loyalty_tiers', ['min_lifetime_points'], unique=False)
    op.drop_index(op.f('ix_loyalty_points_ledger_created_by'), table_name='loyalty_points_ledger')
    op.create_index('idx_loyalty_ledger_order', 'loyalty_points_ledger', ['order_id'], unique=False)
    op.create_index('idx_loyalty_ledger_expires', 'loyalty_points_ledger', ['expires_at'], unique=False)
    op.create_index('idx_loyalty_ledger_event', 'loyalty_points_ledger', ['event_type'], unique=False)
    op.create_index('idx_loyalty_ledger_customer', 'loyalty_points_ledger', ['customer_id'], unique=False)
    op.create_index('idx_loyalty_ledger_created_by', 'loyalty_points_ledger', ['created_by'], unique=False)
    op.create_index('idx_loyalty_ledger_created', 'loyalty_points_ledger', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_loyalty_ledger_account', 'loyalty_points_ledger', ['loyalty_account_id'], unique=False)
    op.create_index('idx_loyalty_accounts_tier', 'loyalty_accounts', ['current_tier_id'], unique=False)
    op.create_index('idx_loyalty_accounts_customer', 'loyalty_accounts', ['customer_id'], unique=True)
    op.drop_index(op.f('ix_inventory_stock_store_id'), table_name='inventory_stock')
    op.drop_index(op.f('ix_inventory_stock_inventory_item_id'), table_name='inventory_stock')
    op.create_index('ix_inventory_stock_store', 'inventory_stock', ['store_id'], unique=False)
    op.create_index('ix_inventory_stock_item', 'inventory_stock', ['inventory_item_id'], unique=False)
    op.drop_index(op.f('ix_inventory_movement_log_performed_by'), table_name='inventory_movement_log')
    op.create_index('idx_inventory_movement_performed_by', 'inventory_movement_log', ['performed_by'], unique=False)
    op.create_index('idx_inv_movement_type', 'inventory_movement_log', ['movement_type'], unique=False)
    op.create_index('idx_inv_movement_store', 'inventory_movement_log', ['store_id'], unique=False)
    op.create_index('idx_inv_movement_reference', 'inventory_movement_log', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_inv_movement_item', 'inventory_movement_log', ['inventory_item_id'], unique=False)
    op.create_index('idx_inv_movement_created', 'inventory_movement_log', ['created_at'], unique=False, postgresql_using='brin')
    op.add_column('inventory_items', sa.Column('store_id_temp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.create_index('idx_inventory_supplier', 'inventory_items', ['supplier_id'], unique=False)
    op.create_index('idx_inv_categories_parent', 'inventory_categories', ['parent_category_id'], unique=False)
    op.create_index('idx_info_cards_type', 'information_cards', ['content_type'], unique=False)
    op.create_index('idx_info_cards_slug', 'information_cards', ['slug'], unique=False)
    op.create_index('idx_iam_roles_scope', 'iam_roles', ['scope_level'], unique=False)
    op.create_index('idx_iam_principals_type', 'iam_principals', ['principal_type'], unique=False)
    op.create_index('idx_iam_principals_status', 'iam_principals', ['status'], unique=False)
    op.create_index('idx_iam_principals_deleted_at', 'iam_principals', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_iam_permissions_resource_action', 'iam_permissions', ['resource', 'action'], unique=False)
    op.alter_column('feedback_entries', 'replied_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('feedback_entries', 'customer_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('uq_event_rsvps_event_customer', 'event_rsvps', ['event_id', 'customer_id'], unique=True)
    op.alter_column('event_rsvps', 'customer_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('event_cards', 'rsvp_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('event_cards', 'rsvp_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_equipment_maintenance_logs_equipment_id'), table_name='equipment_maintenance_logs')
    op.create_index('idx_equipment_maintenance_logs_equipment_id', 'equipment_maintenance_logs', ['equipment_id'], unique=False)
    op.drop_index(op.f('ix_equipment_store_id'), table_name='equipment')
    op.create_index('idx_equipment_store_id', 'equipment', ['store_id'], unique=False)
    op.create_index('idx_dining_tables_store', 'dining_tables', ['store_id'], unique=False)
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_index('idx_customers_segment', 'customers', ['customer_segment'], unique=False)
    op.create_index('idx_customers_referred_by', 'customers', ['referred_by_customer_id'], unique=False)
    op.create_index('idx_customers_referral_code', 'customers', ['referral_code'], unique=True, postgresql_where='(referral_code IS NOT NULL)')
    op.create_index('idx_customers_phone', 'customers', ['phone_number'], unique=True, postgresql_where='((phone_number IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index('idx_customers_lifetime_value', 'customers', [sa.literal_column('lifetime_value DESC')], unique=False)
    op.create_index('idx_customers_email', 'customers', ['email_address'], unique=True, postgresql_where='((email_address IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index('idx_customers_deleted_at', 'customers', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_customers_created_at', 'customers', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'customer_vouchers', type_='foreignkey')
    op.create_foreign_key('customer_vouchers_store_id_fkey', 'customer_vouchers', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_customer_vouchers_voucher_code', table_name='customer_vouchers')
    op.create_index('idx_customer_vouchers_store', 'customer_vouchers', ['store_id'], unique=False)
    op.create_index('idx_customer_vouchers_status', 'customer_vouchers', ['status'], unique=False)
    op.create_index('idx_customer_vouchers_order', 'customer_vouchers', ['order_id'], unique=False)
    op.create_index('idx_customer_vouchers_expires', 'customer_vouchers', ['expires_at'], unique=False)
    op.create_index('idx_customer_vouchers_definition', 'customer_vouchers', ['voucher_definition_id'], unique=False)
    op.create_index('idx_customer_vouchers_customer', 'customer_vouchers', ['customer_id'], unique=False)
    op.drop_constraint(None, 'customer_rewards', type_='foreignkey')
    op.create_foreign_key('customer_rewards_store_id_fkey', 'customer_rewards', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_customer_rewards_store', 'customer_rewards', ['store_id'], unique=False)
    op.create_index('idx_customer_rewards_status', 'customer_rewards', ['status'], unique=False)
    op.create_index('idx_customer_rewards_order', 'customer_rewards', ['order_id'], unique=False)
    op.create_index('idx_customer_rewards_expires', 'customer_rewards', ['expires_at'], unique=False)
    op.create_index('idx_customer_rewards_customer', 'customer_rewards', ['customer_id'], unique=False)
    op.create_index('idx_customer_rewards_code', 'customer_rewards', ['redemption_code'], unique=True)
    op.create_index('idx_customer_rewards_catalog', 'customer_rewards', ['reward_catalog_id'], unique=False)
    op.drop_constraint(None, 'customer_devices', type_='unique')
    op.create_index('idx_customer_devices_fingerprint', 'customer_devices', ['device_fingerprint'], unique=True)
    op.create_index('idx_customer_devices_customer', 'customer_devices', ['customer_id'], unique=False)
    op.create_index('idx_customer_devices_active', 'customer_devices', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.drop_constraint(None, 'customer_daily_checkins', type_='foreignkey')
    op.create_foreign_key('customer_daily_checkins_customer_id_fkey', 'customer_daily_checkins', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_customer_daily_checkins_customer_id'), table_name='customer_daily_checkins')
    op.create_index('idx_checkins_date', 'customer_daily_checkins', ['checkin_date'], unique=False)
    op.create_index('idx_checkins_customer', 'customer_daily_checkins', ['customer_id'], unique=False)
    op.create_unique_constraint('customer_daily_checkins_customer_id_checkin_date_key', 'customer_daily_checkins', ['customer_id', 'checkin_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('customer_daily_checkins', 'checkin_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('customer_daily_checkins', 'customer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index('idx_customer_consents_unique', 'customer_consents', ['customer_id', 'consent_type', 'consent_version'], unique=True)
    op.create_index('idx_customer_consents_type', 'customer_consents', ['consent_type'], unique=False)
    op.create_index('idx_customer_consents_status', 'customer_consents', ['status'], unique=False)
    op.create_index('idx_customer_consents_customer', 'customer_consents', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_customer_carts_store_id'), table_name='customer_carts')
    op.create_index('idx_customer_carts_unique', 'customer_carts', ['customer_id', 'store_id'], unique=True)
    op.create_index('idx_customer_carts_activity', 'customer_carts', ['last_activity_at'], unique=False)
    op.create_index('idx_customer_addresses_geo', 'customer_addresses', [sa.literal_column('point(longitude::double precision, latitude::double precision)')], unique=False, postgresql_using='gist')
    op.create_index('idx_customer_addresses_default', 'customer_addresses', ['customer_id'], unique=True, postgresql_where='((is_default = true) AND (deleted_at IS NULL))')
    op.create_index('idx_customer_addresses_customer', 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('idx_customer_addresses_country', 'customer_addresses', ['country_code'], unique=False)
    op.create_index('idx_page_sections_page', 'content_sections', ['content_id'], unique=False)
    op.create_index('idx_content_sections_ref', 'content_sections', ['content_type', 'content_id'], unique=False)
    op.drop_index(op.f('ix_cart_line_items_menu_variant_id'), table_name='cart_line_items')
    op.create_index('idx_cart_lines_item', 'cart_line_items', ['menu_item_id'], unique=False)
    op.create_index('idx_cart_lines_cart', 'cart_line_items', ['cart_id'], unique=False)
    op.create_index('idx_cart_line_items_menu_variant', 'cart_line_items', ['menu_variant_id'], unique=False)
    op.create_index('idx_audit_log_store', 'audit_log', ['store_id'], unique=False)
    op.create_index('idx_audit_log_severity', 'audit_log', ['severity'], unique=False)
    op.create_index('idx_audit_log_resource', 'audit_log', ['resource_type', 'resource_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_log_request_id', 'audit_log', ['request_id'], unique=False)
    op.create_index('idx_audit_log_principal', 'audit_log', ['principal_id'], unique=False)
    op.create_index('idx_audit_log_created', 'audit_log', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('idx_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_api_credentials_principal', 'api_credentials', ['principal_id'], unique=False)
    op.create_index('idx_api_credentials_key_hash', 'api_credentials', ['api_key_hash'], unique=True)
    op.create_index('idx_api_credentials_active', 'api_credentials', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('admin_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_notifications', 'created_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'admin_accounts', type_='unique')
    op.create_index('idx_admin_accounts_principal', 'admin_accounts', ['principal_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_admin_accounts_locked_until', 'admin_accounts', ['locked_until'], unique=False)
    op.create_index('idx_admin_accounts_is_active', 'admin_accounts', ['is_active'], unique=False)
    op.create_index('idx_admin_accounts_email', 'admin_accounts', ['email'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_table('checkout_sessions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cart_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('applied_voucher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applied_reward_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('delivery_fee', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('completed_order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('device_fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('delivery_fee >= 0::numeric', name='checkout_sessions_delivery_fee_check'),
    sa.CheckConstraint('discount_amount >= 0::numeric', name='checkout_sessions_discount_amount_check'),
    sa.CheckConstraint('subtotal >= 0::numeric', name='checkout_sessions_subtotal_check'),
    sa.CheckConstraint('tax_amount >= 0::numeric', name='checkout_sessions_tax_amount_check'),
    sa.CheckConstraint('total_amount >= 0::numeric', name='checkout_sessions_total_amount_check'),
    sa.ForeignKeyConstraint(['applied_reward_id'], ['reward_catalog.id'], name='checkout_sessions_applied_reward_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['applied_voucher_id'], ['voucher_definitions.id'], name='checkout_sessions_applied_voucher_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_order_id'], ['orders.id'], name='checkout_sessions_completed_order_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='checkout_sessions_customer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='checkout_sessions_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='checkout_sessions_pkey'),
    sa.UniqueConstraint('token_hash', name='checkout_sessions_token_hash_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_checkout_token_hash', 'checkout_sessions', ['token_hash'], unique=True)
    op.create_index('idx_checkout_sessions_store', 'checkout_sessions', ['store_id'], unique=False)
    op.create_index('idx_checkout_sessions_completed_order', 'checkout_sessions', ['completed_order_id'], unique=False)
    op.create_index('idx_checkout_expires', 'checkout_sessions', ['expires_at'], unique=False, postgresql_where='(is_completed = false)')
    op.create_index('idx_checkout_customer', 'checkout_sessions', ['customer_id'], unique=False)
    op.create_table('staff_pin_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], name='staff_pin_attempts_staff_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='staff_pin_attempts_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='staff_pin_attempts_pkey')
    )
    op.create_index('idx_pin_attempts_time', 'staff_pin_attempts', ['attempted_at'], unique=False)
    op.create_index('idx_pin_attempts_staff', 'staff_pin_attempts', ['staff_id'], unique=False)
    op.create_table('card_gallery_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='card_gallery_images_pkey')
    )
    op.create_index('idx_gallery_card', 'card_gallery_images', ['card_type', 'card_id'], unique=False)
    op.create_table('customer_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customer_favorites_customer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name='customer_favorites_menu_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='customer_favorites_pkey'),
    sa.UniqueConstraint('customer_id', 'menu_item_id', name='customer_favorites_customer_id_menu_item_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_customer_favorites_item', 'customer_favorites', ['menu_item_id'], unique=False)
    op.create_index('idx_customer_favorites_customer', 'customer_favorites', ['customer_id'], unique=False)
    op.create_table('otp_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resend_available_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('send_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('verify_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('delivery_provider', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('send_count >= 1', name='otp_sessions_send_count_check'),
    sa.CheckConstraint('verify_attempts >= 0', name='otp_sessions_verify_attempts_check'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='otp_sessions_customer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='otp_sessions_pkey'),
    sa.UniqueConstraint('session_token', name='otp_sessions_session_token_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_otp_sessions_token', 'otp_sessions', ['session_token'], unique=False)
    op.create_index('idx_otp_sessions_phone', 'otp_sessions', ['phone_number'], unique=False)
    op.create_index('idx_otp_sessions_customer', 'otp_sessions', ['customer_id'], unique=False)
    # ### end Alembic commands ###
