"""add_pos_terminal_session_and_order_modification_log

Revision ID: e636778a8401
Revises: c2d3e4f5a6b7
Create Date: 2026-05-17 20:49:08.200618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e636778a8401'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_terminals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('terminal_code', sa.String(length=50), nullable=False),
    sa.Column('location_label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('store_id > 0', name='ck_pos_terminals_store_id'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_code')
    )
    op.create_index(op.f('ix_pos_terminals_store_id'), 'pos_terminals', ['store_id'], unique=False)
    op.create_table('pos_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('terminal_id', sa.BigInteger(), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discrepancy', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discrepancy_notes', sa.Text(), nullable=True),
    sa.Column('total_sales_cash', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_sales_card', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_sales_qr', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open','closed','paused')", name='ck_pos_sessions_status'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['terminal_id'], ['pos_terminals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_sessions_staff_id'), 'pos_sessions', ['staff_id'], unique=False)
    op.create_index(op.f('ix_pos_sessions_terminal_id'), 'pos_sessions', ['terminal_id'], unique=False)
    op.create_table('order_modification_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('modification_type', sa.String(length=30), nullable=False),
    sa.Column('line_item_id', sa.BigInteger(), nullable=True),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("modification_type IN ('add_item','remove_item','update_qty','update_note','apply_discount','remove_discount','update_status')", name='ck_order_modification_logs_type'),
    sa.ForeignKeyConstraint(['line_item_id'], ['order_line_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_modification_logs_line_item_id'), 'order_modification_logs', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_order_modification_logs_order_id'), 'order_modification_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_modification_logs_staff_id'), 'order_modification_logs', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_modification_logs_staff_id'), table_name='order_modification_logs')
    op.drop_index(op.f('ix_order_modification_logs_order_id'), table_name='order_modification_logs')
    op.drop_index(op.f('ix_order_modification_logs_line_item_id'), table_name='order_modification_logs')
    op.drop_table('order_modification_logs')
    op.drop_index(op.f('ix_pos_sessions_terminal_id'), table_name='pos_sessions')
    op.drop_index(op.f('ix_pos_sessions_staff_id'), table_name='pos_sessions')
    op.drop_table('pos_sessions')
    op.drop_index(op.f('ix_pos_terminals_store_id'), table_name='pos_terminals')
    op.drop_table('pos_terminals')
    # ### end Alembic commands ###
