from fastapi import APIRouter

from .admin_dashboard import router as admin_dashboard_router
from .admin_store_management import router as admin_store_management_router
from .admin_menu_management import router as admin_menu_management_router
from .admin_table_management import router as admin_table_management_router
from .admin_customizations import router as admin_customizations_router
from .admin_reports_legacy import router as admin_reports_legacy_router

router = APIRouter()
router.include_router(admin_dashboard_router)
router.include_router(admin_store_management_router)
router.include_router(admin_menu_management_router)
router.include_router(admin_table_management_router)
router.include_router(admin_customizations_router)
router.include_router(admin_reports_legacy_router)
