"""all tables initial

Revision ID: 11d3990efb33
Revises: 395b86453379
Create Date: 2026-04-13 03:30:01.364582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11d3990efb33'
down_revision: Union[str, None] = '395b86453379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
