"""Sync models with DB

Revision ID: c1c045a7bbab
Revises: d25bbe3d82ca
Create Date: 2026-04-20 14:52:59.179558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c1c045a7bbab'
down_revision: Union[str, None] = 'd25bbe3d82ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('audit_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('customization_options', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customization_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_customization_options_id'), 'customization_options', ['id'], unique=False)
    op.alter_column('device_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_device_tokens_token', table_name='device_tokens')
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_feedback_store_created', table_name='feedback')
    op.alter_column('information_cards', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('information_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_information_cards_id', table_name='information_cards')
    op.create_index(op.f('ix_information_cards_id'), 'information_cards', ['id'], unique=False)
    op.drop_column('information_cards', 'action_url')
    op.drop_column('information_cards', 'action_type')
    op.alter_column('inventory_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_inventory_categories_id'), 'inventory_categories', ['id'], unique=False)
    op.alter_column('inventory_items', 'current_stock',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('inventory_items', 'reorder_level',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('inventory_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('inventory_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_inv_movements_store_item', table_name='inventory_movements')
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.alter_column('loyalty_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('loyalty_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('loyalty_tiers', 'points_multiplier',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False)
    op.alter_column('loyalty_tiers', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('loyalty_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_loyalty_tx_created', table_name='loyalty_transactions')
    op.drop_index('ix_loyalty_tx_user_type', table_name='loyalty_transactions')
    op.alter_column('marketing_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_marketing_campaigns_id'), 'marketing_campaigns', ['id'], unique=False)
    op.alter_column('menu_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_items', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_items', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_menu_items_store_category', table_name='menu_items')
    op.alter_column('notification_broadcasts', 'audience',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('notification_broadcasts', 'sent_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notification_broadcasts', 'open_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notification_broadcasts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('notification_broadcasts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.alter_column('order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_order_items_menu_item', table_name='order_items')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.alter_column('order_status_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('orders', 'discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('orders', 'pickup_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('orders', 'loyalty_points_earned',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_store_status', table_name='orders')
    op.drop_index('ix_orders_table_id', table_name='orders')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.alter_column('otp_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('otp_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('payment_methods', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_pin_attempts_staff_window', table_name='pin_attempts')
    op.alter_column('promo_banners', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('promo_banners', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('referrals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('rewards', 'total_redeemed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rewards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('rewards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('splash_content', 'active_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('splash_content', 'active_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('splash_content', 'fallback_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('splash_content', 'fallback_subtitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('splash_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('splash_content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('staff', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('uq_staff_store_user', table_name='staff', postgresql_where='(user_id IS NOT NULL)')
    op.alter_column('staff_shifts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_staff_shifts_staff_clockout', table_name='staff_shifts')
    op.alter_column('store_tables', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stores', 'pickup_lead_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stores', 'delivery_radius_km',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('stores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_stores_active', table_name='stores')
    op.alter_column('survey_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('survey_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('survey_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('surveys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('table_occupancy_snapshot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_table_occupancy_store_occupied', table_name='table_occupancy_snapshot')
    op.alter_column('token_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('user_rewards', 'redeemed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_user_rewards_redemption_code', table_name='user_rewards')
    op.create_unique_constraint(None, 'user_rewards', ['redemption_code'])
    op.alter_column('user_store_access', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('user_store_access', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_user_store_access_store', table_name='user_store_access')
    op.drop_index('ix_user_store_access_user', table_name='user_store_access')
    op.alter_column('user_vouchers', 'applied_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_user_vouchers_code', table_name='user_vouchers')
    op.create_unique_constraint(None, 'user_vouchers', ['code'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('vouchers', 'min_spend',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('vouchers', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vouchers', 'valid_from',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('vouchers', 'valid_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('vouchers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_wallet_tx_created', table_name='wallet_transactions')
    op.drop_index('ix_wallet_tx_wallet_type', table_name='wallet_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wallet_tx_wallet_type', 'wallet_transactions', ['wallet_id', 'type'], unique=False)
    op.create_index('ix_wallet_tx_created', 'wallet_transactions', ['created_at'], unique=False)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vouchers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vouchers', 'valid_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('vouchers', 'valid_from',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('vouchers', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vouchers', 'min_spend',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'user_vouchers', type_='unique')
    op.create_index('ix_user_vouchers_code', 'user_vouchers', ['code'], unique=True)
    op.alter_column('user_vouchers', 'applied_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_user_store_access_user', 'user_store_access', ['user_id'], unique=False)
    op.create_index('ix_user_store_access_store', 'user_store_access', ['store_id'], unique=False)
    op.alter_column('user_store_access', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_store_access', 'assigned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'user_rewards', type_='unique')
    op.create_index('ix_user_rewards_redemption_code', 'user_rewards', ['redemption_code'], unique=True)
    op.alter_column('user_rewards', 'redeemed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_addresses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.alter_column('token_blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_table_occupancy_store_occupied', 'table_occupancy_snapshot', ['store_id', 'is_occupied'], unique=False)
    op.alter_column('table_occupancy_snapshot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('surveys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('survey_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('survey_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('survey_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_stores_active', 'stores', ['is_active'], unique=False)
    op.alter_column('stores', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('stores', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stores', 'delivery_radius_km',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('stores', 'pickup_lead_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('store_tables', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_staff_shifts_staff_clockout', 'staff_shifts', ['staff_id', 'clock_out'], unique=False)
    op.alter_column('staff_shifts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index('uq_staff_store_user', 'staff', ['store_id', 'user_id'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.alter_column('staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('staff', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('splash_content', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('splash_content', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('splash_content', 'fallback_subtitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('splash_content', 'fallback_title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('splash_content', 'active_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('splash_content', 'active_from',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('rewards', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('rewards', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('rewards', 'total_redeemed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referrals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('promo_banners', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('promo_banners', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_pin_attempts_staff_window', 'pin_attempts', ['staff_id', 'attempted_at'], unique=False)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payment_methods', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('otp_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('otp_sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_orders_table_id', 'orders', ['table_id'], unique=False)
    op.create_index('ix_orders_store_status', 'orders', ['store_id', 'status'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'loyalty_points_earned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'pickup_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('orders', 'discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('orders', 'delivery_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('order_status_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.create_index('ix_order_items_menu_item', 'order_items', ['menu_item_id'], unique=False)
    op.alter_column('order_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notification_broadcasts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('notification_broadcasts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('notification_broadcasts', 'open_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notification_broadcasts', 'sent_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notification_broadcasts', 'audience',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('ix_menu_items_store_category', 'menu_items', ['store_id', 'category_id'], unique=False)
    op.alter_column('menu_items', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_items', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_marketing_campaigns_id'), table_name='marketing_campaigns')
    op.alter_column('marketing_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_loyalty_tx_user_type', 'loyalty_transactions', ['user_id', 'type'], unique=False)
    op.create_index('ix_loyalty_tx_created', 'loyalty_transactions', ['created_at'], unique=False)
    op.alter_column('loyalty_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('loyalty_tiers', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('loyalty_tiers', 'points_multiplier',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
    op.alter_column('loyalty_accounts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('loyalty_accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.create_index('ix_inv_movements_store_item', 'inventory_movements', ['store_id', 'inventory_item_id'], unique=False)
    op.alter_column('inventory_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'reorder_level',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('inventory_items', 'current_stock',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_inventory_categories_id'), table_name='inventory_categories')
    op.alter_column('inventory_categories', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('information_cards', sa.Column('action_type', sa.VARCHAR(length=20), server_default=sa.text("'detail'::character varying"), autoincrement=False, nullable=True))
    op.add_column('information_cards', sa.Column('action_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_information_cards_id'), table_name='information_cards')
    op.create_index('idx_information_cards_id', 'information_cards', ['id'], unique=False)
    op.alter_column('information_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('information_cards', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_feedback_store_created', 'feedback', ['store_id', 'created_at'], unique=False)
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('favorites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_device_tokens_token', 'device_tokens', ['token'], unique=True)
    op.alter_column('device_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_customization_options_id'), table_name='customization_options')
    op.alter_column('customization_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customization_options', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cart_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('audit_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('app_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
