"""Pydantic v2 schemas for API request/response validation."""

from app.schemas.auth import (
    AdminLoginRequest,
    AuthResponse,
    CustomerLoginRequest,
    CustomerRegisterRequest,
    OTPRequest,
    OTPVerifyRequest,
    PasswordResetConfirm,
    PasswordResetRequest,
    RefreshTokenRequest,
    StaffLoginRequest,
    TokenPair,
    TokenPayload,
)
from app.schemas.base import (
    APIResponse,
    BaseSchema,
    IDSchema,
    PaginatedResponse,
    PaginationParams,
    TimestampedSchema,
)
from app.schemas.cart import (
    CartLineItemCreate,
    CartLineItemOut,
    CartLineItemUpdate,
    CartModifierSelection,
    CheckoutSessionOut,
    CustomerCartOut,
)
from app.schemas.customer import (
    CustomerAddressCreate,
    CustomerAddressOut,
    CustomerAddressUpdate,
    CustomerConsentOut,
    CustomerDeviceOut,
    CustomerMeOut,
    CustomerProfileCreate,
    CustomerProfileOut,
    CustomerProfileUpdate,
)
from app.schemas.loyalty import (
    CustomerRewardOut,
    LoyaltyAccountOut,
    LoyaltyPointsLedgerOut,
    LoyaltyTierOut,
    RewardCatalogBase,
    RewardCatalogCreate,
    RewardCatalogOut,
    RewardCatalogUpdate,
)
from app.schemas.menu import (
    AllergenOut,
    DietaryTagBase,
    DietaryTagCreate,
    DietaryTagOut,
    DietaryTagUpdate,
    MenuCategoryCreate,
    MenuCategoryOut,
    MenuCategoryUpdate,
    MenuItemCreate,
    MenuItemOut,
    MenuItemPublicOut,
    MenuItemRecipeOut,
    MenuItemUpdate,
    MenuModifierGroupOut,
    MenuModifierOptionOut,
    MenuPublicOut,
    MenuVariantOut,
    TaxCategoryBase,
    TaxCategoryCreate,
    TaxCategoryOut,
    TaxCategoryUpdate,
)
from app.schemas.order import (
    OrderAdjustmentOut,
    OrderCreate,
    OrderFulfillmentOut,
    OrderLineItemOut,
    OrderListParams,
    OrderOut,
    OrderStatusLogOut,
)
from app.schemas.payment import (
    PaymentIntentRequest,
    PaymentIntentResponse,
    PaymentMethodOut,
    PaymentOut,
    PaymentWebhookPayload,
    RefundOut,
)
from app.schemas.store import (
    DiningTableOut,
    StoreBase,
    StoreConfigurationOut,
    StoreCreate,
    StoreListParams,
    StoreOperatingHoursOut,
    StoreOut,
    StorePublicOut,
    StoreSpecialHoursOut,
    StoreUpdate,
)
from app.schemas.audit import AuditLogOut
from app.schemas.notification import (
    AdminNotificationCreate,
    NotificationDeliveryLogOut,
    NotificationMessageOut,
    NotificationPreferenceOut,
    NotificationPreferenceUpdate,
)
from app.schemas.voucher import (
    CustomerVoucherOut,
    VoucherApplyRequest,
    VoucherDefinitionCreate,
    VoucherDefinitionOut,
    VoucherDefinitionUpdate,
)
from app.schemas.content import (
    SplashScreenCreate,
    SplashScreenOut,
    SplashScreenUpdate,
    InfoCardBase,
    InfoCardCreate,
    InfoCardUpdate,
    InfoCardOut,
    ProductCardBase,
    ProductCardCreate,
    ProductCardUpdate,
    ProductCardOut,
    EventCardBase,
    EventCardCreate,
    EventCardUpdate,
    EventCardOut,
    SystemPageBase,
    SystemPageCreate,
    SystemPageUpdate,
    SystemPageOut,
    PromoBannerBase,
    PromoBannerCreate,
    PromoBannerUpdate,
    PromoBannerOut,
    ContentSectionBase,
    ContentSectionOut,
)
from app.schemas.marketing import (
    MarketingCampaignCreate,
    MarketingCampaignOut,
    MarketingCampaignUpdate,
)
from app.schemas.referral import (
    ReferralEventCreate,
    ReferralEventOut,
)
from app.schemas.reservation import (
    ReservationCreate,
    ReservationOut,
    ReservationUpdate,
)
from app.schemas.survey import (
    SurveyDefinitionCreate,
    SurveyDefinitionDetailOut,
    SurveyDefinitionOut,
    SurveyDefinitionUpdate,
    SurveyQuestionCreate,
    SurveyQuestionOut,
    SurveyQuestionUpdate,
    SurveyResponseCreate,
    SurveyResponseOut,
)
from app.schemas.wallet import (
    TopUpRequest,
    WalletLedgerEntryOut,
    WalletOut,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampedSchema",
    "APIResponse",
    "PaginationParams",
    "PaginatedResponse",
    "IDSchema",
    # Auth
    "TokenPair",
    "TokenPayload",
    "CustomerRegisterRequest",
    "CustomerLoginRequest",
    "OTPRequest",
    "OTPVerifyRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "RefreshTokenRequest",
    "AdminLoginRequest",
    "StaffLoginRequest",
    "AuthResponse",
    # Customer
    "CustomerProfileCreate",
    "CustomerProfileOut",
    "CustomerProfileUpdate",
    "CustomerAddressCreate",
    "CustomerAddressOut",
    "CustomerAddressUpdate",
    "CustomerDeviceOut",
    "CustomerConsentOut",
    "CustomerMeOut",
    # Store
    "StoreBase",
    "StoreCreate",
    "StoreUpdate",
    "StoreOut",
    "StorePublicOut",
    "StoreOperatingHoursOut",
    "StoreSpecialHoursOut",
    "StoreConfigurationOut",
    "DiningTableOut",
    "StoreListParams",
    # Menu
    "AllergenOut",
    "MenuCategoryCreate",
    "MenuCategoryUpdate",
    "MenuCategoryOut",
    "MenuItemCreate",
    "MenuItemUpdate",
    "MenuItemOut",
    "MenuItemPublicOut",
    "MenuItemRecipeOut",
    "MenuModifierGroupOut",
    "MenuModifierOptionOut",
    "MenuVariantOut",
    "MenuPublicOut",
    "DietaryTagBase",
    "DietaryTagCreate",
    "DietaryTagOut",
    "DietaryTagUpdate",
    "TaxCategoryBase",
    "TaxCategoryCreate",
    "TaxCategoryOut",
    "TaxCategoryUpdate",
    # Cart
    "CartModifierSelection",
    "CartLineItemCreate",
    "CartLineItemUpdate",
    "CartLineItemOut",
    "CustomerCartOut",
    "CheckoutSessionOut",
    # Order
    "OrderCreate",
    "OrderOut",
    "OrderLineItemOut",
    "OrderStatusLogOut",
    "OrderAdjustmentOut",
    "OrderFulfillmentOut",
    "OrderListParams",
    # Payment
    "PaymentMethodOut",
    "PaymentOut",
    "RefundOut",
    "PaymentIntentRequest",
    "PaymentIntentResponse",
    "PaymentWebhookPayload",
    # Wallet
    "WalletOut",
    "WalletLedgerEntryOut",
    "TopUpRequest",
    # Loyalty
    "LoyaltyTierOut",
    "LoyaltyAccountOut",
    "LoyaltyPointsLedgerOut",
    "RewardCatalogBase",
    "RewardCatalogCreate",
    "RewardCatalogOut",
    "RewardCatalogUpdate",
    "CustomerRewardOut",
    # Voucher
    "VoucherDefinitionCreate",
    "VoucherDefinitionOut",
    "VoucherDefinitionUpdate",
    "CustomerVoucherOut",
    "VoucherApplyRequest",
    # Audit
    "AuditLogOut",
    # Notification
    "NotificationMessageOut",
    "NotificationDeliveryLogOut",
    "NotificationPreferenceOut",
    "NotificationPreferenceUpdate",
    "AdminNotificationCreate",
    # Content
    "SplashScreenCreate",
    "SplashScreenOut",
    "SplashScreenUpdate",
    "InfoCardBase",
    "InfoCardCreate",
    "InfoCardOut",
    "ProductCardBase",
    "ProductCardCreate",
    "ProductCardOut",
    "EventCardBase",
    "EventCardCreate",
    "EventCardOut",
    "SystemPageBase",
    "SystemPageCreate",
    "SystemPageOut",
    "PromoBannerBase",
    "PromoBannerCreate",
    "PromoBannerOut",
    "ContentSectionBase",
    "ContentSectionOut",
    # Marketing
    "MarketingCampaignCreate",
    "MarketingCampaignOut",
    "MarketingCampaignUpdate",
    # Referral
    "ReferralEventCreate",
    "ReferralEventOut",
    # Reservation
    "ReservationCreate",
    "ReservationOut",
    "ReservationUpdate",
    # Survey
    "SurveyDefinitionCreate",
    "SurveyDefinitionDetailOut",
    "SurveyDefinitionOut",
    "SurveyDefinitionUpdate",
    "SurveyQuestionCreate",
    "SurveyQuestionOut",
    "SurveyQuestionUpdate",
    "SurveyResponseCreate",
    "SurveyResponseOut",
]
